import { Assets, AssetsManifest } from "pixi.js";
import * as PIXI from "pixi.js";
import { Tile, BaseTileKey } from "./tile";
import { Season } from "./time-manager";
import { Biome, BiomeId, Biomes } from "./biomes";
import { Species } from "./species";

export interface CachedTexture {
  url: string;
  xOffset: number;
  yOffset: number;
}

export const AssetSeasons = [Season.Spring];

/** List of assets grouped in bundles, for dynamic loading */
let assetsManifest: AssetsManifest = { bundles: [] };

/** Store bundles already loaded */
const loadedBundles: string[] = [];

const tileFormat = new Intl.NumberFormat("en", {
  minimumIntegerDigits: 2,
  useGrouping: false,
});

/** Check if a bundle exists in assetManifest  */
function CheckBundleExists(bundle: string) {
  return !!assetsManifest.bundles.find((b) => b.name === bundle);
}

/** Load assets bundles that have nott been loaded yet */
export async function LoadBundles(bundles: string | string[]) {
  if (typeof bundles === "string") bundles = [bundles];

  // Check bundles requested if they exists
  for (const bundle of bundles) {
    if (!CheckBundleExists(bundle)) {
      throw new Error(`[Assets] Invalid bundle: ${bundle}`);
    }
  }

  // Filter out bundles already loaded
  const loadList = bundles.filter((bundle) => !loadedBundles.includes(bundle));

  // Skip if there is no bundle left to be loaded
  if (!loadList.length) return;

  // Load bundles
  console.log("[Assets] Load:", loadList.join(", "));
  await Assets.loadBundle(loadList);

  // Append loaded bundles to the loaded list
  loadedBundles.push(...loadList);
}

/** Check if all bundles are loaded, return false if any of them is not loaded yet  */
export function AreBundlesLoaded(bundles: string[]) {
  for (const name of bundles) {
    // Return false if a single bundle is not present in the loaded list
    if (!loadedBundles.includes(name)) {
      return false;
    }
  }

  // All provided bundles are loaded
  return true;
}

/** Load the assets json manifest generated by assetpack */
async function FetchAssetsManifest(url: string) {
  const response = await fetch(url);
  const manifest = await response.json();
  if (!manifest.bundles) {
    throw new Error("[Assets] Invalid assets manifest");
  }
  return manifest;
}

/** Initialise and start background loading of all assets that don't require renderer */
export async function InitAssetsStage1() {
  initPixiOptions();
  console.log("Start loading assets...");
  // Load assets manifest
  assetsManifest = await FetchAssetsManifest("public/assets-manifest.json");
  console.log("assets manifest length: " + assetsManifest.bundles.length);

  // Init PixiJS assets with this asset manifest
  await Assets.init({ manifest: assetsManifest, basePath: "public" });

  // Load an initial bundle (can use for loading screen in future)
  await LoadBundles("default");

  // List all existing bundles names
  const allBundles = assetsManifest.bundles.map((item) => item.name);

  // Start up background loading of all bundles
  // Assets.backgroundLoadBundle(allBundles);

  await Assets.backgroundLoadBundle(allBundles);
  ProcessTilesetsIntoTiles();
}

/** generate assets that require render (i.e. custom textures using renderTextures) */

export async function InitAssetsStage2(app: PIXI.Application) {
  Species.processSpecies(app);
}

export function initPixiOptions(): void {
  PIXI.BaseTexture.defaultOptions.scaleMode = PIXI.SCALE_MODES.NEAREST;
  PIXI.BaseTexture.defaultOptions.anisotropicLevel = 0;
  PIXI.BaseTexture.defaultOptions.mipmap = PIXI.MIPMAP_MODES.ON;
  PIXI.BaseTexture.defaultOptions.wrapMode = PIXI.WRAP_MODES.CLAMP;
}

export function ProcessTilesetsIntoTiles() {
  // for each tileset, create new Tile 0 through 47
  Object.keys(Biomes.Biomes).forEach((biomeId: BiomeId) => {
    generateTileset(Biomes.Biomes[biomeId]);
  });
  console.log("Final processed Tilesets: ", Tile.Tilesets);
}

export function generateTileset(biomeDef: Biome) {
  const autoTilePrefix = biomeDef.autotilePrefix;
  if (autoTilePrefix) {
    for (let j = 0; j < 48; j++) {
      const tilesetUrl = `${autoTilePrefix}${tileFormat.format(j)}`;
      addTileToTileset(tilesetUrl, biomeDef, j, Tile.currentId++);
    }
  }
  addTileToTileset(biomeDef.baseTile, biomeDef, BaseTileKey, Tile.currentId++);
}

export function getCachedTileTexture(sprite: string): CachedTexture {
  const cachedTexture: PIXI.Texture = PIXI.Cache.get(sprite);
  if (cachedTexture) {
    return {
      url: cachedTexture.baseTexture.resource.src,
      xOffset: cachedTexture.frame.x,
      yOffset: cachedTexture.frame.y,
    };
  }
  return null;
}

export function getTextureURL(texture: PIXI.Texture): CachedTexture {
  if (texture) {
    return {
      url: texture.baseTexture.resource.src,
      xOffset: texture.frame.x,
      yOffset: texture.frame.y,
    };
  }
  return null;
}

function addTileToTileset(
  spritePath: string,
  tilesetMeta: Biome,
  tileIndex: number | string,
  tileId: number
) {
  // add entry for tileset if it doesn't already exist.
  // it could exist already if other seasons have been added
  if (!Tile.Tilesets[tilesetMeta.id]) {
    Tile.Tilesets[tilesetMeta.id] = {};
  }

  for (const season of AssetSeasons) {
    if (!Tile.Tilesets[tilesetMeta.id][season]) {
      // add entry for season if it doesn't already exist
      Tile.Tilesets[tilesetMeta.id][season] = {};
    }
    // add the generated tile to the tileset object
    Tile.Tilesets[tilesetMeta.id][season][tileIndex] = tileId;
  }
  Tile.textures[tileId] = PIXI.Texture.from(spritePath);
}
