name: Build Project and Publish to itch.io
on:
  push:
    branches:
      - itch
env:
  ITCH_USERNAME: seifer8ff
  ITCH_GAME_ID: sim-world
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.20.7]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build:assets --if-present
      - run: npm run build --if-present

      # 👇 Store the dist folder
      - uses: actions/upload-artifact@v4
        with:
          name: webgl
          path: dist
  deploy:
    needs: [build]
    name: Deploy - Itch.io
    strategy:
      fail-fast: true
      matrix:
        channel:
          - webgl
    runs-on: ubuntu-latest
    steps:
      # 👇 Get the dist folder
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.channel }}
          path: dist/
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_CREDENTIALS}}
          gameData: ./dist/
          itchUsername: ${{env.ITCH_USERNAME}}
          itchGameId: ${{ env.ITCH_GAME_ID }}
          buildChannel: ${{ matrix.channel }}
